language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jbv1995/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jbv1995/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-138859164733"
    bucket_path: "docker-react"
    on:
        branch: master